# -*- coding: utf-8 -*-
"""GICS 子產業 / 部門的中文對照表。查不到就原樣保留英文。"""

SECTOR_ZH = {
    "Information Technology": "資訊科技", "Health Care": "醫療保健",
    "Financials": "金融", "Consumer Discretionary": "非必需消費",
    "Communication Services": "通訊服務", "Industrials": "工業",
    "Consumer Staples": "必需消費", "Energy": "能源",
    "Utilities": "公用事業", "Real Estate": "房地產", "Materials": "原物料",
}

SUB_ZH = {
    # ---- Information Technology ----
    "Semiconductors": "半導體", "Semiconductor Materials & Equipment": "半導體設備及材料",
    "Application Software": "應用軟體", "Systems Software": "系統軟體",
    "Technology Hardware, Storage & Peripherals": "電腦硬體與儲存",
    "Electronic Equipment & Instruments": "電子設備及儀器",
    "Electronic Components": "電子零組件",
    "Electronic Manufacturing Services": "電子代工服務",
    "Communications Equipment": "通訊設備",
    "IT Consulting & Other Services": "資訊顧問服務",
    "Data Processing & Outsourced Services": "資料處理服務",
    "Internet Services & Infrastructure": "網路服務與基礎設施",
    "Technology Distributors": "科技通路",
    # ---- Health Care ----
    "Pharmaceuticals": "製藥", "Biotechnology": "生物科技",
    "Health Care Equipment": "醫療設備", "Health Care Supplies": "醫療耗材",
    "Health Care Services": "醫療服務", "Health Care Facilities": "醫療機構",
    "Health Care Distributors": "醫療通路",
    "Managed Health Care": "健康保險",
    "Life Sciences Tools & Services": "生命科學工具",
    "Health Care REITs": "醫療不動產信託",
    # ---- Financials ----
    "Diversified Banks": "綜合銀行", "Regional Banks": "區域銀行",
    "Asset Management & Custody Banks": "資產管理與託管",
    "Investment Banking & Brokerage": "投資銀行與券商",
    "Financial Exchanges & Data": "交易所與金融數據",
    "Transaction & Payment Processing Services": "支付處理",
    "Consumer Finance": "消費金融",
    "Property & Casualty Insurance": "產險", "Life & Health Insurance": "壽險",
    "Multi-line Insurance": "綜合保險", "Insurance Brokers": "保險經紀",
    "Reinsurance": "再保險", "Multi-Sector Holdings": "多元控股",
    # ---- Consumer Discretionary ----
    "Automobile Manufacturers": "汽車製造", "Automotive Parts & Equipment": "汽車零組件",
    "Broadline Retail": "綜合零售", "Homebuilding": "住宅建商",
    "Home Improvement Retail": "居家修繕零售", "Specialty Stores": "專門店",
    "Apparel Retail": "服飾零售", "Automotive Retail": "汽車零售",
    "Computer & Electronics Retail": "電子產品零售",
    "Restaurants": "餐飲", "Hotels, Resorts & Cruise Lines": "旅宿與郵輪",
    "Casinos & Gaming": "博弈", "Leisure Facilities": "休閒設施",
    "Leisure Products": "休閒用品", "Footwear": "鞋類",
    "Apparel, Accessories & Luxury Goods": "服飾與精品",
    "Household Appliances": "家用電器", "Home Furnishings": "家具家飾",
    "Housewares & Specialties": "家庭用品", "Distributors": "經銷商",
    "Education Services": "教育服務", "Other Specialty Retail": "其他專門零售",
    # ---- Communication Services ----
    "Interactive Media & Services": "互動媒體與服務",
    "Movies & Entertainment": "影視娛樂", "Interactive Home Entertainment": "互動娛樂",
    "Cable & Satellite": "有線與衛星電視", "Broadcasting": "廣播電視",
    "Publishing": "出版", "Advertising": "廣告",
    "Integrated Telecommunication Services": "綜合電信",
    "Wireless Telecommunication Services": "無線電信",
    # ---- Industrials ----
    "Aerospace & Defense": "航空航天與國防",
    "Industrial Machinery & Supplies & Components": "工業機械與零組件",
    "Construction Machinery & Heavy Transportation Equipment": "營建機械與重型設備",
    "Agricultural & Farm Machinery": "農業機械",
    "Electrical Components & Equipment": "電氣設備及零件",
    "Heavy Electrical Equipment": "重電設備",
    "Building Products": "建材產品", "Construction & Engineering": "營造與工程",
    "Trading Companies & Distributors": "貿易與經銷",
    "Industrial Conglomerates": "工業集團",
    "Environmental & Facilities Services": "環境與設施服務",
    "Human Resource & Employment Services": "人力資源服務",
    "Research & Consulting Services": "研究顧問服務",
    "Diversified Support Services": "多元支援服務",
    "Air Freight & Logistics": "航空貨運與物流", "Passenger Airlines": "客運航空",
    "Rail Transportation": "鐵路運輸", "Cargo Ground Transportation": "陸運貨運",
    "Marine Transportation": "海運", "Passenger Ground Transportation": "陸運客運",
    # ---- Consumer Staples ----
    "Packaged Foods & Meats": "包裝食品與肉品", "Agricultural Products & Services": "農產品",
    "Soft Drinks & Non-alcoholic Beverages": "軟性飲料",
    "Distillers & Vintners": "酒商", "Brewers": "釀酒",
    "Tobacco": "菸草", "Household Products": "家庭清潔用品",
    "Personal Care Products": "個人護理用品",
    "Consumer Staples Merchandise Retail": "民生零售",
    "Food Distributors": "食品通路", "Food Retail": "食品零售",
    "Drug Retail": "藥品零售",
    # ---- Energy ----
    "Integrated Oil & Gas": "石油及天然氣綜合",
    "Oil & Gas Exploration & Production": "石油及天然氣勘探與開發",
    "Oil & Gas Refining & Marketing": "石油煉製與行銷",
    "Oil & Gas Storage & Transportation": "石油及天然氣中游",
    "Oil & Gas Equipment & Services": "油氣設備與服務",
    "Coal & Consumable Fuels": "煤炭與燃料",
    # ---- Utilities ----
    "Electric Utilities": "電力公用", "Multi-Utilities": "綜合公用",
    "Gas Utilities": "天然氣公用", "Water Utilities": "自來水公用",
    "Independent Power Producers & Energy Traders": "獨立電廠與能源交易",
    "Renewable Electricity": "再生能源發電",
    # ---- Real Estate ----
    "Industrial REITs": "工業不動產信託", "Retail REITs": "零售不動產信託",
    "Residential REITs": "住宅不動產信託", "Office REITs": "辦公室不動產信託",
    "Data Center REITs": "資料中心不動產信託",
    "Telecom Tower REITs": "電信基地台信託",
    "Timber REITs": "林地不動產信託", "Hotel & Resort REITs": "旅宿不動產信託",
    "Self-Storage REITs": "自助倉儲信託", "Other Specialized REITs": "其他特殊信託",
    "Real Estate Services": "不動產服務",
    "Diversified REITs": "多元不動產信託",
    # ---- Materials ----
    "Specialty Chemicals": "特用化學", "Commodity Chemicals": "大宗化學",
    "Diversified Chemicals": "綜合化學", "Industrial Gases": "工業氣體",
    "Fertilizers & Agricultural Chemicals": "肥料與農用化學",
    "Steel": "鋼鐵", "Aluminum": "鋁業", "Copper": "銅業",
    "Gold": "黃金", "Precious Metals & Minerals": "貴金屬與礦業",
    "Construction Materials": "營建材料",
    "Metal, Glass & Plastic Containers": "金屬玻璃塑膠容器",
    "Paper & Plastic Packaging Products & Materials": "紙類與塑膠包裝",
    "Paper Products": "紙製品", "Forest Products": "林產品",
    # ---- 對照維基實際清單後補上的 ----
    "Consumer Electronics": "消費性電子",
    "Health Care Technology": "醫療科技",
    "Homefurnishing Retail": "家具家飾零售",
    "Multi-Family Residential REITs": "多戶住宅信託",
    "Single-Family Residential REITs": "單戶住宅信託",
    "Specialized Consumer Services": "特殊消費服務",
}

def zh_sector(s): return SECTOR_ZH.get(s, s)
def zh_sub(s):    return SUB_ZH.get(s, s)
